import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'msedge' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('pageerror', e => console.log('PAGEERROR', e.message));
p.on('console', m => { if (m.type() === 'error') console.log('console.error:', m.text().slice(0, 160)); });
const t0 = Date.now();
await p.goto('http://localhost:5199/');
await p.waitForTimeout(2500);
await p.screenshot({ path: 'scripts/x01-land.png' });
// first-time player: click the obvious hero CTA
const cta = p.getByText("LET'S GET TO WORK", { exact: false }).first();
console.log('hero CTA visible:', await cta.isVisible().catch(() => false));
await cta.click().catch(e => console.log('cta click fail', e.message.slice(0, 80)));
await p.waitForTimeout(2000);
await p.screenshot({ path: 'scripts/x02-after-cta.png' });
console.log('scrollY after CTA', await p.evaluate(() => scrollY));
await p.getByPlaceholder('Your fixer alias').fill('Timi');
await p.getByRole('button', { name: /START THE FIRST JOB/ }).click();
await p.waitForTimeout(1200);
await p.screenshot({ path: 'scripts/x03-brief.png' });
await p.locator('.brief-side').getByRole('button', { name: 'Roll tape', exact: true }).click(); await p.getByRole('button', { name: /Freeze frame/ }).click();
const tLab = Date.now();
await p.waitForFunction(() => /\d:\d\d/.test(document.querySelector('.timer')?.textContent || ''), null, { timeout: 40000 });
console.log('editor ready after ms', Date.now() - tLab);
await p.screenshot({ path: 'scripts/x04-lab.png' });
await p.getByTestId('native-tool-shapes').click();
await p.waitForTimeout(1000);
await p.screenshot({ path: 'scripts/x05-shapes.png' });
await p.getByTestId('native-tool-stickers').click();
await p.waitForTimeout(1500);
await p.screenshot({ path: 'scripts/x06-stickers.png' });
const ids = await p.evaluate(() => [...document.querySelectorAll('[data-testid]')].map(e => e.dataset.testid).slice(0, 80));
console.log(ids.join(' '));
await b.close();
