import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'msedge' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('pageerror', e => console.log('PAGEERROR', e.message));
p.on('console', m => { if (m.type() === 'error') console.log('console.error:', m.text().slice(0, 200)); });
await p.goto('http://localhost:5199/');
await p.waitForSelector('.figure', { timeout: 20000 });
await p.waitForTimeout(2500);
await p.screenshot({ path: 'scripts/h1.png' });
await p.click('.carousel-dots button:nth-child(1)');
await p.waitForTimeout(900);
await p.screenshot({ path: 'scripts/h2.png' });
await p.screenshot({ path: 'scripts/h3.png', fullPage: true });
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
await m.goto('http://localhost:5199/');
await m.waitForSelector('.figure', { timeout: 20000 });
await m.waitForTimeout(2000);
await m.screenshot({ path: 'scripts/h4-mobile.png', fullPage: false });
console.log('scrollW', await m.evaluate(() => document.documentElement.scrollWidth));
await b.close();
